version: '1.0'
# Stages can help you organize your steps in stages
stages:
  - 'clone'
  - 'build'
  - 'push'

steps:
  clone:
    title: 'Cloning repository'
    type: 'git-clone'
    repo: 'philzona/fast_image_build'
    revision: '${{CF_BRANCH}}'
    git: 'github-cf'
    stage: 'clone'

  build:
    title: 'Building Docker image'
    stage: 'build'
    type: 'build'
    working_directory: '${{clone}}'
    image_name: 'codefreshphil/fast_image_build'
    tags:
      - latest
      - ${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
    registry: 'dockerhub'

  sonarqube:
    type: "sonar-scanner-cli"
    stage: "push"
    arguments:
      SONAR_HOST_URL: 'https://sonarcloud.io/' # replace with your host url
      SONAR_LOGIN: '${{SONAR_TOKEN}}' # replace with your access token
      SONAR_PROJECT_BASE_DIR: '${{CF_REPO_NAME}}' #r eplace with your working directory
      SONAR_SCANNER_CLI_VERSION: "latest"
