version: '1.0'
# Stages can help you organize your steps in stages
stages:
  - 'clone'
  - 'build'
  - 'push'

steps:
  clone:
    title: 'Cloning repository'
    type: 'git-clone'
    repo: 'philzona/fast_image_build'
    revision: '${{CF_BRANCH}}'
    git: 'github-cf'
    stage: 'clone'

  build:
    title: 'Building Docker image'
    stage: 'build'
    type: 'build'
    working_directory: '${{clone}}'
    image_name: 'codefreshphil/fast_image_build'
    tags:
      - latest
      - ${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
    registry: 'dockerhub'

  push:
    title: 'Pushing to Docker Hub'
    type: 'push'
    stage: 'push'
    registry: 'dockerhub'
    candidate: ${{ build }}
    image_name: 'codefreshphil/fast_image_build'
    tags:
      - latest
      - ${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
